### ISSUE TITLE
connection reset error report

### ISSUE THREAD

**Issue by negoguy** [DMarby/humblebundle-ebook-downloader#23]
I was trying to fetch all my title when a connection reset popped up. The next few attemps to lauch the tool sent me 502 errors.

Error details:
```
Downloading Humble Book Bundle: Programmable Boards by Make: - Making Things See: 3D vision with Kinect, Processing, Arduino, and MakerBot (EPUB) (10.5 MB)... (762/1595)
An error occured, exiting.
{ Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:623:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
PS C:\Users\edemers\Desktop\humblebundlebooks> humblebundle-ebook-downloader -d ./ --debug --all
Starting...
Validating session...
An error occured, exiting.
Error: Could not validate session, unknown error, status code: 502
    at Request.request.get [as _callback] (C:\Users\edemers\AppData\Roaming\npm\node_modules\humblebundle-ebook-downloader\index.js:114:17)
    at Request.self.callback (C:\Users\edemers\AppData\Roaming\npm\node_modules\humblebundle-ebook-downloader\node_modules\request\request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (C:\Users\edemers\AppData\Roaming\npm\node_modules\humblebundle-ebook-downloader\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (C:\Users\edemers\AppData\Roaming\npm\node_modules\humblebundle-ebook-downloader\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

After waiting 10 minutes or so i was able to launch the tool again without error. This happened 2 or 3 times so far and i suppose it may be my network's fault or a humhub's session expiration policy (since i have a VERY large library). This is more to inform you with the error stack than to report an actual bug since i'm still able to use the tool and resume where it crashed.

**Comment by BernhardHH** [comment]
This ECONNRESET error keeps popping up very frequently, I have to restart the tool 2-4 times to get one download through. Could you maybe incorporate some internal retry counter before giving up?
