### ISSUE TITLE
How to download bundle if I wasn't logged in when I purchased?

### ISSUE THREAD

**Issue by lestephane** [DMarby/humblebundle-ebook-downloader#37]
When I purchased my last bundle, i only provided an email address.

So I received a link by email to download the bundle without the intermediate login step.

Then pasted the email link in the browser location bar, then copied the `_simpleauth_sess` cookie value and used that, to no avail

```bash
humblebundle-ebook-downloader --format pdf --download-limit 1 --auth-token "${_simpleauth_sess}"
Starting...
Validating session...
An error occured, exiting.
Error: Could not validate session, unknown error, status code: 401
    at Request.request.get [as _callback] (/usr/local/lib/node_modules/humblebundle-ebook-downloader/index.js:114:17)
    at Request.self.callback (/usr/local/lib/node_modules/humblebundle-ebook-downloader/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/humblebundle-ebook-downloader/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/humblebundle-ebook-downloader/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

The only thing that looks weird in the auth token are these characters right before the first vertical bar. This could create all sorts of escaping nightmares with my download command.

```text
...\075\075|
```

Has anyone managed to successfully download an 'anonymous' bundle (one purchased without a login)? Is there any trick i should know?

**Comment by DMarby** [comment]
Hi,

You will need to create an account, and claim the bundle to your account. 
Then you should be able to copy the cookie value when logged in, and use the tool.

Instructions for how to do the claiming can be found at https://support.humblebundle.com/hc/en-us/articles/203523930-How-to-claim-a-Humble-Bundle-purchase-or-gift
