### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by gesicmerrybeard** [DMarby/humblebundle-ebook-downloader#45]
Is it possible to get ARM support for the new Apple Silicon devices?

```
npm install -g humblebundle-ebook-downloader
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/humblebundle-ebook-downloader/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
Downloading electron-v2.0.18-darwin-arm64.zip
npm ERR! Error: GET https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip returned 404
npm ERR! /opt/homebrew/lib/node_modules/humblebundle-ebook-downloader/node_modules/electron/install.js:54
npm ERR!   throw err
npm ERR!   ^
npm ERR!
npm ERR! Error: Failed to find Electron v2.0.18 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/opt/homebrew/lib/node_modules/humblebundle-ebook-downloader/node_modules/nugget/index.js:169:61)
npm ERR!     at Request.emit (node:events:379:20)
npm ERR!     at Request.onRequestResponse (/opt/homebrew/lib/node_modules/humblebundle-ebook-downloader/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:379:20)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:668:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:534:22)
npm ERR!     at TLSSocket.emit (node:events:379:20)
npm ERR!     at addChunk (node:internal/streams/readable:313:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:288:9)
```

**Comment by Tokariew** [comment]
https://github.com/Tokariew/hb_downloader <-- little self plug, but it should run fine on M1 Mac…
